### ISSUE TITLE
class dont le nom commence par une minuscule

### ISSUE THREAD

**Issue by Kushalatreon** [Capablanca4/Intelligence---artificielle#5]

**Comment by Kushalatreon** [comment]
Okay, en regardant un peu le code, j'ai vu que certaines classes avaient un nom qui commençait par une minuscule, celles-ci sont des classes toutes faites que tu as trouvé sur Internet Pierre? Si c'est le cas, ça veut dire qu'on aura pas besoin d'effectuer de tests dessus n'est-ce pas?

**Comment by Capablanca4** [comment]
Alors mes classes ( celles que j'ai mis dans l'UML ) ont toutes des noms en majuscule:
comme case est un mot réservé du langage j'ai préféré mettre une majuscule pour être sur.
A partir de là j'ai donc adopté cette convention pour être régulier et cohérent

**Comment by Capablanca4** [comment]
Les classes avec une minuscule sont donc des classes importées (à part viewPort qui m'a été donné par philipe et donc ne contenait pas de majuscule à la base)
